### ISSUE TITLE
Add Koalas support for properties and methods not explicitly defined in woodwork.

### ISSUE THREAD

**Issue by ctduffy** [alteryx/woodwork#374] opened 2020-11-11 20:34 UTC
We can use this extend functionality to allow methods and properties not explicitly written for our Woodwork DataTables to be used for DataTables with Koalas dataframes as the underlying data type.

https://koalas.readthedocs.io/en/latest/reference/extensions.html

**Comment by tyler3991** [comment] 2021-02-01 20:52
Closing. Duplicate of #493

**Closed by tyler3991** 2021-02-01 20:52 UTC
Labels: new feature
