### ISSUE TITLE
Datetime format is not stored on columns where series dtype doesn't change

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#1138] opened 2021-09-10 16:31 UTC
In #1021 , the datetime format was meant to be saved on any column with the logical type `Datetime`. Looking at the place where this happens in [Datetime's transform method](https://github.com/alteryx/woodwork/blob/main/woodwork/logical_types.py#L203), the format only gets saved if the dtype of the series has to change or if a datetime format was passed into the LogicalType. This means that there are instances where the datetime format is not stored in the resulting column on the DataFrame.

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd 
from woodwork.logical_types import Datetime

datetimes_df = pd.DataFrame({
     'dates_inferred_same_dtype':[pd.to_datetime('2020-09-01')] * 4,
     'dates_inferred_change_dtype':['2020-09-01'] * 4,
    'dates_set_without_format_same_dtype':[pd.to_datetime('2020-09-01')] * 4,
    'dates_set_without_format_change_dtype': ['2020-09-01'] * 4,
    'dates_set_with_format_same_dtype': [pd.to_datetime('2020-09-01')] * 4,
    'dates_set_with_format_change_dtype':['2020-09-01'] * 4,
})
print(datetimes_df.dtypes)

datetimes_df.ww.init(logical_types={'dates_set_with_format_same_dtype':Datetime(datetime_format='%Y-%m-%d'), 
                                    'dates_set_with_format_change_dtype':Datetime(datetime_format='%Y-%m-%d'), 
                                    'dates_set_without_format_change_dtype':Datetime,
                                    'dates_set_without_format_same_dtype':Datetime,
                                   })

print({col:schema.logical_type.datetime_format for col, schema in datetimes_df.ww.columns.items()})

```

The result is that the datetime formats are as follows:
```python
{'dates_inferred_same_dtype': None,
 'dates_inferred_change_dtype': '%Y-%m-%d',
 'dates_set_without_format_same_dtype': None,
 'dates_set_without_format_change_dtype': '%Y-%m-%d',
 'dates_set_with_format_same_dtype': '%Y-%m-%d',
 'dates_set_with_format_change_dtype': '%Y-%m-%d'}
```
Notice that the two columns where no format is set are the ones whose dtypes were already `datetime64[ns]` before woodwork init when no `datetime_format` parameter was passed into the logical type.

We should add a test that checks that the datetime formats are actually accessible on the resulting DataFrame and that they're always set.

**Comment by thehomebrewnerd** [comment] 2021-09-10 16:36
I might be remembering things a bit wrong at this point, but I think we were only saving the format in circumstances where we inferred what the format was. If a series is already a datetime when it is passed to Woodwork, Woodwork is not making any assumptions about what that format is, so in those cases we do not save the format.

**Comment by tuethan1999** [comment] 2021-09-10 16:40
Yes I believe that was the intended behavior

**Comment by tamargrey** [comment] 2021-09-10 16:42
Ah, interesting. I guess that wasn't clear to me from looking at the issue, but it makes sense to me in that context of not needing to do this check if Woodwork didn't change the dtype. 

t does seem to be a little unexpected if you don't have that context, though, so it might be worth adding a comment above that line explaining the intended behavior. Or maybe in the `Datetime` docstring so that users can know when to expect `Datetime.datetime_format` to be present and what it means.

**Comment by gsheni** [comment] 2021-11-12 20:46
This is intended behavior. Closing

**Closed by gsheni** 2021-11-12 20:46 UTC
Labels: bug
